version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash wait-for-it/wait-for-it.sh -t 15 db:5432 -- python fooddiary/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
